# Python for data Analysis

Python is a programming language widely used by developers and data scientists. It is particularly popular because it is:<br><br>
Easy to use<br>
Has simple syntax that helps readability<br>
It is easy to learn and quick to adapt to<br>
Data can be presented in different forms such as CSV, JSON, Excel files and database etc.<br>
Python is very efficient in processing and wrangling most data types.


## Numpy Array and vectorization
Numpy is python library for numerical computations for arrays and multidimensional matrices in data analysis

In [32]:
import numpy as np

In [33]:
#creating an array
arr = [6,7,8,9]

#printing the data type
print(type(arr)) 

<class 'list'>


In [34]:
#creating a numpy array
a = np.array(arr)

In [35]:
print(type(a))

<class 'numpy.ndarray'>


In [36]:
a.shape

(4,)

Interpretation:
The data has 4 items

In [37]:
a.dtype

dtype('int32')

In [38]:
#get the dimension of the array
a.ndim

1

a is a 1-dimensional array

This is a one dimensional array with 4 items

In [39]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#dimension of array
b.ndim

2

In [41]:
#shape of array
b.shape

(2, 3)

b has 2 rows and 3 columns

In [42]:
#check the python data type
type(b)

numpy.ndarray

In [43]:
#check the data type
b.dtype

dtype('int32')

#### Inbuilt functions that can be used to initialize arrays

In [44]:
# 2*3 array with random values
np.random.random((2,3))

array([[0.45151679, 0.15270684, 0.67362766],
       [0.85777642, 0.47471785, 0.05924678]])

In [45]:
# 2*3 array with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# 2*3 array with ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# 3*3 identity matrix
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Interoperability of arrays and scalars

In [48]:
c =np.array([[9.,8.0,7.0], [1.0,2.0,3.0]])
d =np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [49]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [50]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [51]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [52]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

#### Indexing using arrays

In [54]:
a = [6,7,8,9]
a[0]

6

In [55]:
a[3]

9

In [58]:
b = np.array([[1,2,3],[4,5,6]])
b[0,0]

1

In [59]:
b[1,2]

6

In [60]:
b[0,1]

2

In [61]:
d =np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
d[1, 0:2]

array([9., 8.])

In [62]:
e = np.array([[10,11,12],[13,14,15],
              [16,17,18],[19,20,21]])

In [63]:
#slicing
e[:3 , :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [65]:
#integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [66]:
#boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

## Pandas
Pandas is a toolkit built on numpy with data structures called dataframes; used on numerical and time series data for quick and easy manipulation, cleaning and analysis<br><br>
Series, DataFrame and Index are the basic data structures in this library. Series in pandas can be referred to as a 1-dimensional array with homogeneous elements of different types somewhat similar to numpy arrays; however, it can be indexed differently with specified descriptive labels or integers.<br><br>
A DataFrame can be described a table(2-dimensions) made up of many series with the same index.

In [68]:
import pandas as pd

#### Series

In [69]:
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])
days

0       Monday
1      Tuesday
2    Wednesday
dtype: object

In [70]:
#creating a series with numpy array
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days =pd.Series(days_list)
numpy_days

0       Monday
1      Tuesday
2    Wednesday
dtype: object

In [72]:
#using strings as index
days =pd.Series(['Monday', 'Tuesday', 'Wednesday'],
                index = ['a','b','c'])
days

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [73]:
#create a series from a dictionary
days1 = pd.Series({'a': 'Monday',
                   'b': 'Tuesday',
                   'c': 'Wednesday'}
                  )
days

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [74]:
#accessing Series
days[0]

'Monday'

In [75]:
days[1:]

b      Tuesday
c    Wednesday
dtype: object

In [76]:
days['c']

'Wednesday'

#### DataFrame

In [78]:
print(pd.DataFrame())


Empty DataFrame
Columns: []
Index: []


In [88]:
#creating a dataframe from a dictionary
our_dict ={'Country': ['Ghana','Kenya','Nigeria','Togo'],
          'Capital': ['Accra','Nairobi','Abuja','Lome'],
          'Population': [10000, 8500, 35000, 12000],
          'Age':[60,70,80,75]
    
}

#creating the dataframe from the dictionary above
df =pd.DataFrame(our_dict, index =[2,4,6,8])

In [84]:
df

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome        1200   75

In [92]:
#creating a dataframe from a list
#creating a dataframe from a dictionary
our_list =[['Ghana','Accra',1000,60],
            ['Kenya','Nairobi',8500, 70],
            ['Nigeria','Abuja', 35000,80],
            ['Togo','Lome',12000,75]
            ]
    


#creating the dataframe from the list above
df =pd.DataFrame(our_list,
                 columns = ['Country','Capital','Population','Age'],
                 index =[2,4,6,8]
                 )
df

Country  Capital  Population  Age
2    Ghana    Accra        1000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

#### Indexing in dataframes

In [93]:
#selecting row in dex 3
df.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [94]:
#slect row with index label 6
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [95]:
#select capital column
df['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [97]:
#Select value at index 6 in the Country column
df.at[6, 'Country']

'Nigeria'

In [99]:
#select value at index (2,0)
df.iat[2,0]

'Nigeria'

In [101]:
#Sum of the population
df['Population'].sum()

56500

In [104]:
#Mean of numeric variables
df.mean(numeric_only= True)

Population    14125.00
Age              71.25
dtype: float64

In [105]:
#statistical features of the dataframe
df.describe()

Population        Age
count      4.000000   4.000000
mean   14125.000000  71.250000
std    14653.640048   8.539126
min     1000.000000  60.000000
25%     6625.000000  67.500000
50%    10250.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

In [107]:
#transposing the statistical results
df.describe().transpose()

count      mean           std     min     25%      50%       75%  \
Population    4.0  14125.00  14653.640048  1000.0  6625.0  10250.0  17750.00   
Age           4.0     71.25      8.539126    60.0    67.5     72.5     76.25   

                max  
Population  35000.0  
Age            80.0

In [110]:
#Creating a new dataframe from a dictionary
our_dict2 = { 'Name':['James','Yemen','Caro', np.nan],
             'Profession':['Reseracher', 'Artist','Doctor','Writer'],
             'Experience':[12, np.nan,10,8],
             'Height':[np.nan,175,180,150]   
}
df1 = pd.DataFrame(our_dict2)
df1

Name  Profession  Experience  Height
0  James  Reseracher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [111]:
#check for null values
df1.isnull()

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [127]:
#Check for null values
df1.isnull().sum()

Name          1
Profession    0
Experience    1
Height        1
dtype: int64

In [125]:
#Display only columns with null values
df1.isnull().sum()[df1.isnull().sum() >0]

Name          1
Experience    1
Height        1
dtype: int64

In [126]:
#List of columns with null values
df1.columns[df1.isnull().any()].tolist()

['Name', 'Experience', 'Height']